### ISSUE TITLE
Wow, you've completely gone overboard with this

### ISSUE THREAD

**Issue by Kaldaien** [marcussacana/FAR#1]
The lengths you go to in order to assert I have malicious code anywhere in the entire project astounds me :-\

If you would read the source code, instead of going through all this absolutely ridiculous cleanroom style reverse engineering of the DLL, you'd actually see a few lines of code that you're missing if you want Special K to think you're completely clean. Rather than nop'ing stuff out, you should just remove several lines of code at the same time you'd see why the lengths you are going to are astounding. I spent all of five minutes on this, I don't know what you think I'm capable of in five minutes, but it's none of this nonsense.

There are no crash triggers, crashing occurs largely for two reasons:

 1. Flimsy ass fake SteamAPI implementation crumbles to pieces when modified
 2. The pirated binary is older than the retail version, and you should be using an older version of the mod as your base unless you want to add pattern scanning (be my guest).

You're searching for unicorns where there are none.

Again, I do nothing malicious. It's rather funny you go on to describe corrupting the cracked version of any game, because that's not something I've ever done. EVERYTHING is transparent as can be in C++ code.

<hr>

Regarding the crash handler, MGS Alert sound, stack traces can be found in logs/crash.log, that's the entire purpose of the crash handler. I don't know how useful it will be in a binary-modified executable, some of the line numbers may be off -- but you don't appear to be distributing the debug database with your mod anyway, so nobody's going to make heads or tails of those crash logs :)

Also you have not removed my name, and I'm not happy about that 👎

**Comment by marcussacana** [comment]
i'm testing by now other method, hmmm... so, are you angry?
Man, i don't sent any takedown request to your repo, and i don't try say have a malicious code into your git, just i think in the possibility from you releasing a binary with a code different from the source, waiting for me to debug and fuck me (maybe a checksum validation) <3 just this, i use the ProcMon to analyze if the mod try delete my crack, and other random shit... 
You like if i remove your name, so?
Really i don't know what i can try, first, i don't have plans to stop to support the piracy, in the same time i don't feel anything bad to about you now, i just... I just feel feather of you.
You writed this fucking mod, a really good work, but you act as kid sometimes, (i saying this can looks funny because my bad eng) The piracy is a big, but very big community, you are just one. If you try to get in the way, it's obvious they'll be irritated. 
Or did you think they would thank you?
Did you want to survive of the entire community of thousands of people all over the world?
maybe the github received too many takedown request and just delete your repo...
Pay attention, in life, in this world .... there are things in which you must not compete and just accept.
Otherwise, things like that can happen.

**Comment by Kaldaien** [comment]
I never asked you to stop supporting whatever it is you're supporting.

I'm telling you as bluntly as I can that the source code is available, you would save yourself a tremendous amount of trouble if you referred to it rather than believing the absolutely wild things you do about how the software functions. I've actually documented all the measures I've taken, I'v never hidden anything, but you're coming up with off-the-wall crazy things that my code supposedly does because you're looking at the compiled executable and not making much headroom from the looks of things.

Again, I will re-iterate, your two biggest obstacles to stability are not me, they are:

1. Fake SteamAPI
2. Outdated executable

Please, focus your attention there or you're going to waste tremendous amounts of effort for no apparent reason. I've put things in my code to disable SteamAPI, and an older version of FAR exists that you can use as your base to ensure stability.

I am being polite with you, I don't have any obligation to do this you know. I don't even know WHY I'm doing it given the way you respond.

But please, remove my name. It's the least you could do. I know you don't respect anything or anyone, but from one coder to another maybe? Just freaking remove my name.

**Comment by marcussacana** [comment]
Okay, Sorry for anything, and thanks for the mod and the hint.

**Comment by nbmrjuhneibkr** [comment]
Sorry for reopening this, but I just wanted to say that the cracked binary is not outdated, actually.
