### ISSUE TITLE
New releases?

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [marcussacana/FAR#11]
The latest version here is 0.6.2.0, while the official release is already at 0.6.2.10.

**Comment by marcussacana** [comment]
I say in other issue, because some problems i format my computer, actually i have my translation project to work and i can´t stop to setup the nier again because the brazil internet is a trash and i need maybe 5~6 days to download it again.
So for now, i can´t publish... i can crack, but i can´t test it.

**Comment by DStrifer** [comment]
yep! stop pushing him!) Hi will do it eventually, we hope and believe) no matter how long. :)

**Comment by marcussacana** [comment]
if you like use without test, i can crack and upload here, but nothing of auto-update...

**Comment by DStrifer** [comment]
We can try) But u know, the point of FAR (for me) is to set only one parameter from Ultra (128) to High (64), that's enough to boost FPS in my case.  I no need HUD and other things )  Is it possible somehow !?

**Comment by marcussacana** [comment]
exist but you need know inject the code, so.. i think i can say nop.

**Comment by marcussacana** [comment]
i have published the lastest version, only can install with manual update, and isn´t tested... use if you like.
