### ISSUE TITLE
Updated Release?

### ISSUE THREAD

**Issue by slendercraft** [marcussacana/FAR#15]
Could you update it to the newly released 0.7.0.21 version? Or even just update the screenshots in the section where you describe how to do it yourself since Nya.is has been dead for a few months now.

**Comment by marcussacana** [comment]
Since i don't have the nier more i can't test any update....
If you learn you can...
In the SK_PirateAHoy have a variable who store the result, just put a xor eax,eax; ret don't works because this variable isn't set... so now we need patch with a way to he set this variable and not just return...
I will download the nier again when i buy a new joystick, maybe in the end of january?...

**Comment by slendercraft** [comment]
After poking around a bit more, I was able to figure it out.
Thank you still. :)
